namespace: postgres-operator



commonLabels:
  postgres-operator.crunchydata.com/control-plane: postgres-operator

resources:
  - ../../bases

images:
- name: postgres-operator
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi8-5.0.3-0

patches:
  - target:
      kind: Deployment
      name: pgo
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: env
                      operator: In
                      values:
                        - dev
                    - key: app
                      operator: In
                      values:
                        - app
      - op: add
        path: /spec/template/spec/tolerations
        value:
            - key: app
              operator: Equal
              value: app
            - key: env
              operator: Equal
              value: dev
